/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tEthernetOutputTaskBody_template.c => src/tEthernetOutputTaskBody.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * require port : signature: sKernel context: task
 *   ER             sleep( );
 *   ER             sleepTimeout( TMO timeout );
 *   ER             delay( RELTIM delayTime );
 *   ER             exitTask( );
 *   ER             getTaskId( ID* p_taskId );
 *   ER             rotateReadyQueue( PRI taskPriority );
 *   ER             getTime( SYSTIM* p_systemTime );
 *   ER             getMicroTime( SYSUTM* p_systemMicroTime );
 *   ER             lockCpu( );
 *   ER             unlockCpu( );
 *   ER             disableDispatch( );
 *   ER             enableDispatch( );
 *   ER             disableTaskException( );
 *   ER             enableTaskException( );
 *   ER             changeInterruptPriorityMask( PRI interruptPriority );
 *   ER             getInterruptPriorityMask( PRI* p_interruptPriority );
 *   ER             exitKernel( );
 *   bool_t         senseContext( );
 *   bool_t         senseLock( );
 *   bool_t         senseDispatch( );
 *   bool_t         senseDispatchPendingState( );
 *   bool_t         senseKernel( );
 * call port : cSemaphoreSend  signature: sSemaphore context: task
 *   ER             cSemaphoreSend_signal( );
 *   ER             cSemaphoreSend_wait( );
 *   ER             cSemaphoreSend_waitPolling( );
 *   ER             cSemaphoreSend_waitTimeout( TMO timeout );
 *   ER             cSemaphoreSend_initialize( );
 *   ER             cSemaphoreSend_refer( T_RSEM* pk_semaphoreStatus );
 * call port : cDataqueue  signature: sDataqueue context: task
 *   ER             cDataqueue_send( intptr_t data );
 *   ER             cDataqueue_sendPolling( intptr_t data );
 *   ER             cDataqueue_sendTimeout( intptr_t data, TMO timeout );
 *   ER             cDataqueue_sendForce( intptr_t data );
 *   ER             cDataqueue_receive( intptr_t* p_data );
 *   ER             cDataqueue_receivePolling( intptr_t* p_Data );
 *   ER             cDataqueue_receiveTimeout( intptr_t* p_data, TMO timeout );
 *   ER             cDataqueue_initialize( );
 *   ER             cDataqueue_refer( T_RDTQ* pk_dataqueueStatus );
 * call port : cNicDriver  signature: sNicDriver context: task
 *   void           cNicDriver_init( );
 *   void           cNicDriver_start( int8_t* outputp, int32_t size, uint8_t align );
 *   void           cNicDriver_read( int8_t** inputp, int32_t* size, uint8_t align );
 *   void           cNicDriver_getMac( uint8_t* macaddress );
 * call port : cSemTcppost  signature: sSemaphore context: task
 *   ER             cSemTcppost_signal( );
 *   ER             cSemTcppost_wait( );
 *   ER             cSemTcppost_waitPolling( );
 *   ER             cSemTcppost_waitTimeout( TMO timeout );
 *   ER             cSemTcppost_initialize( );
 *   ER             cSemTcppost_refer( T_RSEM* pk_semaphoreStatus );
 * allocator port for call port: cNicDriver func: start param: outputp
 *   ER             cNicDriver_start_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_start_outputp_dealloc( const void* buf );
 *   ER             cNicDriver_start_outputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_start_outputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_start_outputp_bufferMaxSize( );
 * allocator port for call port: cNicDriver func: read param: inputp
 *   ER             cNicDriver_read_inputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_read_inputp_dealloc( const void* buf );
 *   ER             cNicDriver_read_inputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_read_inputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_read_inputp_bufferMaxSize( );
 * allocator port for call port: eRawOutput func: ethernetRawOutput param: outputp
 *   ER             eRawOutput_ethernetRawOutput_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             eRawOutput_ethernetRawOutput_outputp_dealloc( const void* buf );
 *   ER             eRawOutput_ethernetRawOutput_outputp_reuse( void* buf );
 *   ER_UINT        eRawOutput_ethernetRawOutput_outputp_bufferSize( const void* buf );
 *   uint32_t       eRawOutput_ethernetRawOutput_outputp_bufferMaxSize( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tEthernetOutputTaskBody_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eRawOutput
 * entry port: eRawOutput
 * signature:  sEthernetRawOutput
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eRawOutput_ethernetRawOutput
 * name:         eRawOutput_ethernetRawOutput
 * global_name:  tEthernetOutputTaskBody_eRawOutput_ethernetRawOutput
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eRawOutput_ethernetRawOutput(CELLIDX idx, int8_t* outputp, int32_t size,TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	if((ercd = cDataqueue_sendTimeout((intptr_t)outputp,tmout)) != E_OK){
		eRawOutput_ethernetRawOutput_outputp_dealloc((void*)outputp);
		//mikan NICリセットをかける
	}
	return(ercd);
}

/* #[<ENTRY_PORT>]# eBody
 * entry port: eBody
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eBody_main
 * name:         eBody_main
 * global_name:  tEthernetOutputTaskBody_eBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eBody_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	T_NET_BUF	*output;
	ID		tskid;
	int32_t size;

	getTaskId(&tskid);
	syslog(LOG_EMERG, "¥n++++++++Ethernet Output Task Start:%d+++++++++++ ¥n", tskid);

	while (true) {
		while (cDataqueue_receive((intptr_t*)&output) == E_OK) {
			
			
			size = output->len + sizeof(T_NET_BUF) -4 + NETBUFFER_ALIGN;

			syslog(LOG_EMERG, "++++++++++ETHERNET OUTPUT len = %d++++++++++++++",output->len);
		   
			cSemaphoreSend_wait();

			cNicDriver_start((int8_t *)output,size,NETBUFFER_ALIGN);


			//if(is_cSemTcppost_joined())
			  //cSemTcppost_signal();
		}

	}
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
