/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tEthernetOutput_template.c => src/tEthernetOutput.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port : cRawOutput  signature: sEthernetRawOutput context: task
 *   ER             cRawOutput_ethernetRawOutput( int8_t* outputp, int32_t size, TMO tmout );
 * call port : cNicDriver  signature: sNicDriver context: task
 *   void           cNicDriver_init( );
 *   void           cNicDriver_start( int8_t* outputp, int32_t size, uint8_t align );
 *   void           cNicDriver_read( int8_t** inputp, int32_t* size, uint8_t align );
 *   void           cNicDriver_getMac( uint8_t* macaddress );
 * call port : cArpOutput  signature: sArpOutput context: task
 *   ER             cArpOutput_arpResolve( int8_t* outputp, int32_t size, T_IN4_ADDR dstaddr, const uint8_t* macaddress, TMO tmout );
 * allocator port for call port: cRawOutput func: ethernetRawOutput param: outputp
 *   ER             cRawOutput_ethernetRawOutput_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cRawOutput_ethernetRawOutput_outputp_dealloc( const void* buf );
 *   ER             cRawOutput_ethernetRawOutput_outputp_reuse( void* buf );
 *   ER_UINT        cRawOutput_ethernetRawOutput_outputp_bufferSize( const void* buf );
 *   uint32_t       cRawOutput_ethernetRawOutput_outputp_bufferMaxSize( );
 * allocator port for call port: cNicDriver func: start param: outputp
 *   ER             cNicDriver_start_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_start_outputp_dealloc( const void* buf );
 *   ER             cNicDriver_start_outputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_start_outputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_start_outputp_bufferMaxSize( );
 * allocator port for call port: cNicDriver func: read param: inputp
 *   ER             cNicDriver_read_inputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_read_inputp_dealloc( const void* buf );
 *   ER             cNicDriver_read_inputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_read_inputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_read_inputp_bufferMaxSize( );
 * allocator port for call port: cArpOutput func: arpResolve param: outputp
 *   ER             cArpOutput_arpResolve_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cArpOutput_arpResolve_outputp_dealloc( const void* buf );
 *   ER             cArpOutput_arpResolve_outputp_reuse( void* buf );
 *   ER_UINT        cArpOutput_arpResolve_outputp_bufferSize( const void* buf );
 *   uint32_t       cArpOutput_arpResolve_outputp_bufferMaxSize( );
 * allocator port for call port: eEthernetOutput func: ethernetOutput param: outputp
 *   ER             eEthernetOutput_ethernetOutput_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             eEthernetOutput_ethernetOutput_outputp_dealloc( const void* buf );
 *   ER             eEthernetOutput_ethernetOutput_outputp_reuse( void* buf );
 *   ER_UINT        eEthernetOutput_ethernetOutput_outputp_bufferSize( const void* buf );
 *   uint32_t       eEthernetOutput_ethernetOutput_outputp_bufferMaxSize( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tEthernetOutput_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eEthernetOutput
 * entry port: eEthernetOutput
 * signature:  sEthernetOutput
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eEthernetOutput_ethernetOutput
 * name:         eEthernetOutput_ethernetOutput
 * global_name:  tEthernetOutput_eEthernetOutput_ethernetOutput
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eEthernetOutput_ethernetOutput(CELLIDX idx, int8_t* outputp, int32_t size, T_IN4_ADDR dstaddr, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	T_NET_BUF *output = (T_NET_BUF*)outputp;
	uint8_t mymac[6];
	cNicDriver_getMac(mymac);

	/*ヘッダのセット */
	memcpy(GET_ETHER_HDR(output)->shost, mymac, 6);

	if(output->off.protocolflag & FLAG_USE_IPV4){
	GET_ETHER_HDR(output)->type = htons(ETHER_TYPE_IP);
		if(is_cArpOutput_joined())
			return cArpOutput_arpResolve(outputp,size,dstaddr,mymac,tmout);
	}
	else{

		eEthernetOutput_ethernetOutput_outputp_dealloc((void*)outputp);
		return E_PAR;
	}

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
