/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tEthernetInputTaskBody_template.c => src/tEthernetInputTaskBody.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port : cSemaphoreReceive  signature: sSemaphore context: task
 *   ER             cSemaphoreReceive_signal( );
 *   ER             cSemaphoreReceive_wait( );
 *   ER             cSemaphoreReceive_waitPolling( );
 *   ER             cSemaphoreReceive_waitTimeout( TMO timeout );
 *   ER             cSemaphoreReceive_initialize( );
 *   ER             cSemaphoreReceive_refer( T_RSEM* pk_semaphoreStatus );
 * call port : cNicDriver  signature: sNicDriver context: task
 *   void           cNicDriver_init( );
 *   void           cNicDriver_start( int8_t* outputp, int32_t size, uint8_t align );
 *   void           cNicDriver_read( int8_t** inputp, int32_t* size, uint8_t align );
 *   void           cNicDriver_getMac( uint8_t* macaddress );
 * call port : cTaskEthernetOutput  signature: sTask context: task
 *   ER             cTaskEthernetOutput_activate( );
 *   ER_UINT        cTaskEthernetOutput_cancelActivate( );
 *   ER             cTaskEthernetOutput_terminate( );
 *   ER             cTaskEthernetOutput_changePriority( PRI priority );
 *   ER             cTaskEthernetOutput_getPriority( PRI* p_priority );
 *   ER             cTaskEthernetOutput_refer( T_RTSK* pk_taskStatus );
 *   ER             cTaskEthernetOutput_wakeup( );
 *   ER_UINT        cTaskEthernetOutput_cancelWakeup( );
 *   ER             cTaskEthernetOutput_releaseWait( );
 *   ER             cTaskEthernetOutput_suspend( );
 *   ER             cTaskEthernetOutput_resume( );
 *   ER             cTaskEthernetOutput_raiseException( TEXPTN pattern );
 * call port : cTaskNetworkTimer  signature: sTask context: task
 *   ER             cTaskNetworkTimer_activate( );
 *   ER_UINT        cTaskNetworkTimer_cancelActivate( );
 *   ER             cTaskNetworkTimer_terminate( );
 *   ER             cTaskNetworkTimer_changePriority( PRI priority );
 *   ER             cTaskNetworkTimer_getPriority( PRI* p_priority );
 *   ER             cTaskNetworkTimer_refer( T_RTSK* pk_taskStatus );
 *   ER             cTaskNetworkTimer_wakeup( );
 *   ER_UINT        cTaskNetworkTimer_cancelWakeup( );
 *   ER             cTaskNetworkTimer_releaseWait( );
 *   ER             cTaskNetworkTimer_suspend( );
 *   ER             cTaskNetworkTimer_resume( );
 *   ER             cTaskNetworkTimer_raiseException( TEXPTN pattern );
 * call port : cArpInput  signature: sArpInput context: task
 *   void           cArpInput_arpInitialize( );
 *   void           cArpInput_arpInput( int8_t* inputp, int32_t size, const uint8_t* macaddress );
 * call port : cIPv4Input  signature: sIPv4Input context: task
 *   void           cIPv4Input_IPv4Input( int8_t* inputp, int32_t size );
 * allocator port for call port: cNicDriver func: start param: outputp
 *   ER             cNicDriver_start_outputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_start_outputp_dealloc( const void* buf );
 *   ER             cNicDriver_start_outputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_start_outputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_start_outputp_bufferMaxSize( );
 * allocator port for call port: cNicDriver func: read param: inputp
 *   ER             cNicDriver_read_inputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cNicDriver_read_inputp_dealloc( const void* buf );
 *   ER             cNicDriver_read_inputp_reuse( void* buf );
 *   ER_UINT        cNicDriver_read_inputp_bufferSize( const void* buf );
 *   uint32_t       cNicDriver_read_inputp_bufferMaxSize( );
 * allocator port for call port: cArpInput func: arpInput param: inputp
 *   ER             cArpInput_arpInput_inputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cArpInput_arpInput_inputp_dealloc( const void* buf );
 *   ER             cArpInput_arpInput_inputp_reuse( void* buf );
 *   ER_UINT        cArpInput_arpInput_inputp_bufferSize( const void* buf );
 *   uint32_t       cArpInput_arpInput_inputp_bufferMaxSize( );
 * allocator port for call port: cIPv4Input func: IPv4Input param: inputp
 *   ER             cIPv4Input_IPv4Input_inputp_alloc( void** buf, const int32_t minlen, TMO tmout );
 *   ER             cIPv4Input_IPv4Input_inputp_dealloc( const void* buf );
 *   ER             cIPv4Input_IPv4Input_inputp_reuse( void* buf );
 *   ER_UINT        cIPv4Input_IPv4Input_inputp_bufferSize( const void* buf );
 *   uint32_t       cIPv4Input_IPv4Input_inputp_bufferMaxSize( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tEthernetInputTaskBody_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eBody
 * entry port: eBody
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eBody_main
 * name:         eBody_main
 * global_name:  tEthernetInputTaskBody_eBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eBody_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	cNicDriver_init();
	
	/* Ethernet 出力タスクを起動する */
	if(is_cTaskEthernetOutput_joined())
	  cTaskEthernetOutput_activate( );

	/* ネットワークタイマタスクを起動する */
	cTaskNetworkTimer_activate();

	
	/* ARP を初期化する。*/
	if(is_cArpInput_joined())
	  cArpInput_arpInitialize();
	
	
	syslog(LOG_EMERG,"<-------Welcome to Componentized TINET-------->");
	syslog(LOG_EMERG,"****  tEthernetInputTask started  ****");

	T_NET_BUF *input;
	int32_t size;
	uint16_t proto;
	T_ETHER_HDR *eth;
	uint8_t macaddress[6];
	T_OFF_BUF etheroff = {0,0,0,ETHER_HDR_SIZE,ETHER_MTU,NETBUFFER_ALIGN,FLAG_USE_ETHER,0,0};

	while(true){
		cSemaphoreReceive_wait();
		cNicDriver_read((int8_t**)&input,(int32_t*)&size,NETBUFFER_ALIGN);

		input->off = etheroff;

		if(input !=NULL){
			eth = GET_ETHER_HDR(input);
			proto = ntohs(eth->type);


			switch(proto){

			  case ETHER_TYPE_IP:
				if(is_cIPv4Input_joined()){
					cIPv4Input_IPv4Input((int8_t*)input,size);
					break;
				}
				cNicDriver_read_inputp_dealloc((void *)input);
				break;

			  case ETHER_TYPE_ARP:
				if(is_cArpInput_joined()){
					cNicDriver_getMac(macaddress);
					cArpInput_arpInput((int8_t*)input,size,macaddress);
					break;
				}
				cNicDriver_read_inputp_dealloc((void *)input);
				break;

//			  case ETHER_TYPE_IPV6:
//				break;
			  default:
				cNicDriver_read_inputp_dealloc((void *)input);
				break;
			}
		}
	}



}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
