/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tKernel_template.c => src/tKernel.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tKernel_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eTaskGetEntry
 * entry port: eTaskGetEntry
 * signature:  sTaskGetEntry
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eTaskGetEntry_eTaskGetEntry
 * name:         eTaskGetEntry_eTaskGetEntry
 * global_name:  tKernel_eTaskGetEntry_eTaskGetEntry
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eTaskGetEntry_eTaskGetEntry(intptr_t* sTask)
{
}

/* #[<ENTRY_FUNC>]# eTaskGetEntry_eiTaskGetEntry
 * name:         eTaskGetEntry_eiTaskGetEntry
 * global_name:  tKernel_eTaskGetEntry_eiTaskGetEntry
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eTaskGetEntry_eiTaskGetEntry(intptr_t* siTask)
{
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
