/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tNetworkTimer_template.c => src/tNetworkTimer.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * #[<...>]# から #[</...>]# で囲まれたコメントは編集しないでください
 * tecsmerge によるマージに使用されます
 *
 * 属性アクセスマクロ #_CAAM_#
 * timeout          int32_t*         VAR_timeout     
 *
 * 呼び口関数 #_TCPF_#
 * call port: cCallTimerFunction signature: sCallTimerFunction context:task optional:true
 *   bool_t     is_cCallTimerFunction_joined(int subscript)        check if joined
 *   void           cCallTimerFunction_callFunction( subscript );
 *       subscript:  0...(NCP_cCallTimerFunction-1)
 * call port: cTCPTask signature: sTask context:task optional:true
 *   bool_t     is_cTCPTask_joined()                     check if joined
 *   ER             cTCPTask_activate( );
 *   ER_UINT        cTCPTask_cancelActivate( );
 *   ER             cTCPTask_getTaskState( STAT* p_tskstat );
 *   ER             cTCPTask_changePriority( PRI priority );
 *   ER             cTCPTask_getPriority( PRI* p_priority );
 *   ER             cTCPTask_refer( T_RTSK* pk_taskStatus );
 *   ER             cTCPTask_wakeup( );
 *   ER_UINT        cTCPTask_cancelWakeup( );
 *   ER             cTCPTask_releaseWait( );
 *   ER             cTCPTask_suspend( );
 *   ER             cTCPTask_resume( );
 *   ER             cTCPTask_raiseTerminate( );
 *   ER             cTCPTask_terminate( );
 * call port: cSemaphoreNetworkTimer signature: sSemaphore context:task
 *   ER             cSemaphoreNetworkTimer_signal( );
 *   ER             cSemaphoreNetworkTimer_wait( );
 *   ER             cSemaphoreNetworkTimer_waitPolling( );
 *   ER             cSemaphoreNetworkTimer_waitTimeout( TMO timeout );
 *   ER             cSemaphoreNetworkTimer_initialize( );
 *   ER             cSemaphoreNetworkTimer_refer( T_RSEM* pk_semaphoreStatus );
 * call port: ciSemaphoreNetworkTimer signature: siSemaphore context:non-task
 *   ER             ciSemaphoreNetworkTimer_signal( );
 * call port: cSemaphoreCalloutLock signature: sSemaphore context:task
 *   ER             cSemaphoreCalloutLock_signal( );
 *   ER             cSemaphoreCalloutLock_wait( );
 *   ER             cSemaphoreCalloutLock_waitPolling( );
 *   ER             cSemaphoreCalloutLock_waitTimeout( TMO timeout );
 *   ER             cSemaphoreCalloutLock_initialize( );
 *   ER             cSemaphoreCalloutLock_refer( T_RSEM* pk_semaphoreStatus );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tNetworkTimer_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eNetworkTimer
 * entry port: eNetworkTimer
 * signature:  sNetworkTimer
 * context:    task
 * entry port array size:  NEP_eNetworkTimer
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eNetworkTimer_Timeout
 * name:         eNetworkTimer_Timeout
 * global_name:  tNetworkTimer_eNetworkTimer_Timeout
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eNetworkTimer_Timeout(int_t subscript, RELTIM timout)
{
	if(is_cCallTimerFunction_joined(subscript)){
		VAR_timeout[subscript] = timout;
		return E_OK;
	}
	return E_ID;
		
}

/* #[<ENTRY_PORT>]# eBody
 * entry port: eBody
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eBody_main
 * name:         eBody_main
 * global_name:  tNetworkTimer_eBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eBody_main()
{

	int32_t ix;

	syslog(LOG_EMERG,"NetworkTimerTask is working!!");

	if(is_cTCPTask_joined())
	  cTCPTask_activate();

	//接続されているが起動していないタイマを起動
	for(ix = NCP_cCallTimerFunction; ix -- > 0 ;) {
		if(is_cCallTimerFunction_joined(ix) && VAR_timeout ==-1)
		   cCallTimerFunction_callFunction(ix);
	}
	
	while (true) {
		/* タイムアウトしたエントリを呼出す。*/
		cSemaphoreNetworkTimer_wait();
		for (ix = NCP_cCallTimerFunction; ix -- > 0; ) {
			cSemaphoreCalloutLock_wait();
			if (is_cCallTimerFunction_joined(ix) && VAR_timeout[ix] == 0) {
				
				VAR_timeout[ix] = -1;
				cSemaphoreCalloutLock_signal( );
				cCallTimerFunction_callFunction(ix);
				}
			else
				cSemaphoreCalloutLock_signal( );
			}
		}

	
}

/* #[<ENTRY_PORT>]# eiBody
 * entry port: eiBody
 * signature:  siHandlerBody
 * context:    non-task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eiBody_main
 * name:         eiBody_main
 * global_name:  tNetworkTimer_eiBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eiBody_main()
{
	//100ms周期で呼び出されるネットワークタイマ関数
	
	int32_t ix;

	for(ix = N_CP_cCallTimerFunction;ix -- > 0; ){
		if(is_cCallTimerFunction_joined(ix) && VAR_timeout[ix] > 0){
			VAR_timeout[ix]--;
			if(VAR_timeout[ix] == 0)
			  ciSemaphoreNetworkTimer_signal();
		}
	}
	
}

/* #[<POSTAMBLE>]#
 *   これより下に非受け口関数を書きます
 * #[</POSTAMBLE>]#*/
