/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tTest_template.c => src/tTest.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * require port : signature: sKernel context: task
 *   ER             sleep( );
 *   ER             sleepTimeout( TMO timeout );
 *   ER             delay( RELTIM delayTime );
 *   ER             exitTask( );
 *   ER             getTaskId( ID* p_taskId );
 *   ER             rotateReadyQueue( PRI taskPriority );
 *   ER             getTime( SYSTIM* p_systemTime );
 *   ER             getMicroTime( SYSUTM* p_systemMicroTime );
 *   ER             lockCpu( );
 *   ER             unlockCpu( );
 *   ER             disableDispatch( );
 *   ER             enableDispatch( );
 *   ER             disableTaskException( );
 *   ER             enableTaskException( );
 *   ER             changeInterruptPriorityMask( PRI interruptPriority );
 *   ER             getInterruptPriorityMask( PRI* p_interruptPriority );
 *   ER             exitKernel( );
 *   bool_t         senseContext( );
 *   bool_t         senseLock( );
 *   bool_t         senseDispatch( );
 *   bool_t         senseDispatchPendingState( );
 *   bool_t         senseKernel( );
 * call port : cTCPAPI4  signature: sTCPCEPAPI4 context: task
 *   ER             cTCPAPI4_accept( intptr_t sREP4, T_IPV4EP* dstep4, TMO tmout );
 *   ER             cTCPAPI4_connect( T_IN4_ADDR myaddr, uint16_t myport, T_IN4_ADDR dstaddr, uint16_t dstport, TMO tmout );
 *   ER_UINT        cTCPAPI4_send( const int8_t* data, int32_t len, TMO tmout );
 *   ER_UINT        cTCPAPI4_receive( int8_t* data, int32_t len, TMO tmout );
 *   ER             cTCPAPI4_cancel( FN fncd );
 *   ER             cTCPAPI4_close( TMO tmout );
 *   ER             cTCPAPI4_shutdown( );
 * call port : cUDPAPI4  signature: sUDPCEPAPI4 context: task
 *   ER_UINT        cUDPAPI4_send( const int8_t* data, int32_t len, T_IN4_ADDR dstaddr, uint16_t dstport, TMO tmout );
 *   ER_UINT        cUDPAPI4_receive( int8_t* data, int32_t len, TMO tmout );
 *   ER             cUDPAPI4_cancelSend( ER error );
 *   ER             cUDPAPI4_cancelReceive( ER error );
 * call port : cREP4  signature: sREP4 context: task
 *   T_IPV4EP       cREP4_getEndpoint( );
 *   ER             cREP4_signal( );
 *   ER             cREP4_wait( );
 *   ER             cREP4_waitPolling( );
 *   ER             cREP4_waitTimeout( TMO timeout );
 *   ER             cREP4_initialize( );
 *   ER             cREP4_refer( T_RSEM* pk_semaphoreStatus );
 * call port : cREP4_001  signature: sREP4 context: task
 *   T_IPV4EP       cREP4_001_getEndpoint( );
 *   ER             cREP4_001_signal( );
 *   ER             cREP4_001_wait( );
 *   ER             cREP4_001_waitPolling( );
 *   ER             cREP4_001_waitTimeout( TMO timeout );
 *   ER             cREP4_001_initialize( );
 *   ER             cREP4_001_refer( T_RSEM* pk_semaphoreStatus );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tTest_tecsgen.h"
#include "t_syslog.h"
#include "kernel.h"
#include "kernel_cfg.h"
//#include "histogram.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

//dynamic-------
#define cREP4_000_callport (intptr_t)tTest_SINGLE_CELL_CB.cREP4_000
#define cREP4_001_callport (intptr_t)tTest_SINGLE_CELL_CB.cREP4_001
//-------dynamic


#define NUM_SEND_DATA 300
#define COUNT 10000
#define HIST 10000

//static	uint_t histarea[HIST + 1];

/* #[<ENTRY_PORT>]# eTestTask
 * entry port: eTestTask
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eTestTask_main
 * name:         eTestTask_main
 * global_name:  tTest_eTestTask_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eTestTask_main()
{
	ID		tskid;
	ER_UINT		rlen, slen;
	ER		error = E_OK;
	uint32_t i;
	int8_t data[NUM_SEND_DATA];

	getTaskId(&tskid);
	syslog(LOG_EMERG, "Main function started %d.", tskid);
	
	for(i=0;i<NUM_SEND_DATA;i++)
	  data[i] = 10;

	T_IN4_ADDR myaddr = MAKE_IPV4_ADDR(192,168,1,200);
	T_IN4_ADDR dstaddr = MAKE_IPV4_ADDR(192,168,1,201);

	T_IPV4EP dstep4;

	cTCPAPI4_accept(cREP4_000_callport, &dstep4, TMO_FEVR );

	while((rlen = cTCPAPI4_receive(data,100,TMO_FEVR)) > 0){
		data[20] = '\0';
		cTCPAPI4_send(data,rlen,TMO_FEVR);
	}

	syslog(LOG_EMERG, "Main function over %d.", tskid);
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
