/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tUDPCEP4_template.c => src/tUDPCEP4.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * v4addr           T_IN4_ADDR       ATTR_v4addr     
 * addr             T_IN4_ADDR       VAR_addr        
 *
 * call port function #_TCPF_#
 * call port : cAPI  signature: sUDPCEPAPI context: task
 *   ER_UINT        cAPI_send( const int8_t* data, int32_t len, const int8_t* dstaddr, int32_t addrlen, uint16_t dstport, TMO tmout );
 *   ER_UINT        cAPI_receive( int8_t* data, int32_t len, TMO tmout );
 *   ER             cAPI_setFlag( uint32_t flag );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tUDPCEP4_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eAPI4
 * entry port: eAPI4
 * signature:  sUDPCEPAPI4
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eAPI4_send
 * name:         eAPI4_send
 * global_name:  tUDPCEP4_eAPI4_send
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER_UINT
eAPI4_send(CELLIDX idx, const int8_t* data, int32_t len, T_IN4_ADDR dstaddr, uint16_t dstport, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	cAPI_send(data,len,(int8_t*)&dstaddr,4,dstport,tmout);

	return(ercd);
}

/* #[<ENTRY_FUNC>]# eAPI4_receive
 * name:         eAPI4_receive
 * global_name:  tUDPCEP4_eAPI4_receive
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER_UINT
eAPI4_receive(CELLIDX idx, int8_t* data, int32_t len, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	cAPI_receive(data,len,tmout);

	
	return(ercd);
}

/* #[<ENTRY_FUNC>]# eAPI4_setFlag
 * name:         eAPI4_setFlag
 * global_name:  tUDPCEP4_eAPI4_setFlag
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_setFlag(CELLIDX idx, uint32_t flag)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	cAPI_setFlag(flag);

	return(ercd);
}

/* #[<ENTRY_PORT>]# eGetAddress4
 * entry port: eGetAddress4
 * signature:  sGetAddress
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eGetAddress4_getAddress
 * name:         eGetAddress4_getAddress
 * global_name:  tUDPCEP4_eGetAddress4_getAddress
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
int8_t*
eGetAddress4_getAddress(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	return (int8_t*)&VAR_addr;

}

/* #[<ENTRY_FUNC>]# eGetAddress4_getIPversion
 * name:         eGetAddress4_getIPversion
 * global_name:  tUDPCEP4_eGetAddress4_getIPversion
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
int8_t
eGetAddress4_getIPversion(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	return 4;
	
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
